backend:
  name: git-gateway   # easiest with Netlify Identity + Git Gateway
  branch: main        # change if your default branch is different

media_folder: "img/blog"     # uploaded media files live here
public_folder: "/img/blog"  # public path used in the site

publish_mode: editorial_workflow  # uses PRs for safety + review

collections:
  # Single JSON file that powers the blog list in the site
  - label: "Blog"
    name: "blog"
    files:
      - label: "Posts JSON"
        name: "posts"
        file: "data/blog.json"
        format: "json"
        fields:
          - label: "Posts"
            name: "posts"
            widget: "list"
            collapsed: true
            summary: "{{fields.title}} ({{fields.category}})"
            fields:
              - { label: "ID", name: "id", widget: "string", hint: "Stable id, e.g. my-post-slug" }
              - { label: "Title", name: "title", widget: "string" }
              - label: "Category"
                name: "category"
                widget: "select"
                options: ["CTF write-up", "Code snippet", "Research", "How-to", "Notes"]
                default: "Notes"
              - label: "Category Key"
                name: "categoryKey"
                widget: "select"
                options: ["ctf", "snippet", "research", "howto", "notes"]
                default: "notes"
              - { label: "Icon (FontAwesome class)", name: "icon", widget: "string", default: "fa-note-sticky" }
              - { label: "Date", name: "date", widget: "datetime", time_format: false, format: "YYYY-MM-DD" }
              - { label: "Summary", name: "summary", widget: "text" }
              - label: "Body (HTML)"
                name: "bodyHtml"
                widget: "text"
                hint: "You can paste HTML here. The site renders it inside the post modal."
              - label: "Images"
                name: "images"
                widget: "list"
                field: { label: "Image", name: "image", widget: "image" }
              - label: "Tags"
                name: "tags"
                widget: "list"
                field: { label: "Tag", name: "tag", widget: "string" }
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "URL", name: "href", widget: "string" }

